source "https://rubygems.org"

gem 'rails', branch: '4-1-stable'   # Si se cambia -> bundle update rails
gem 'pg'
gem 'jquery-rails'
gem 'haml-rails'
gem 'inherited_resources'
gem 'simple_form'
gem 'better_errors'

group :development do
  gem 'awesome_print'
  gem 'mailcatcher' # Set your app to deliver to smtp://127.0.0.1:1025 instead of your default SMTP server, then check out http://127.0.0.1:1080 to see the mail.
  gem 'rspec-rails'
  gem 'puma'
  gem 'binding_of_caller'
  gem 'meta_request' # Necesario para la extensión 'RailsPanel' de Google Chrome
end
